# Miyadaiku config file

# Base URL of the site
site_url: https://drillan.github.io

# Title of the site
site_title: drillerの部屋

# Default language code
lang: ja

# Default charset
charset: utf-8

# Default timezone
timezone: Asia/Tokyo

copyright: Copyright  © 2020 driller

favicon: /static/amx004.png

# Default page description
og_description: どりらんの落書き帳

# Default page image file
og_image: /static/amx004.png

# site logo
site_logo: /static/amx004.png

# List of site theme
themes:
  - miyadaiku_theme_newblog

